name: Publish to PyPI
on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Replace with the Python version you want to use

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install wheel

      - name: Install twine
        run: pip install twine

        # No requirements!  
      - name: Build and Publish
        run: |
          python setup.py sdist bdist_wheel
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__  
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}  # No need to change here! Edit it in github website.